[package]

name = "quire"
description = "A YAML-based configuration parsing library"
license = "MIT/Apache-2.0"
readme = "README.rst"
keywords = ["config", "yaml", "parser"]
homepage = "http://github.com/tailhook/rust-quire"
version = "0.1.7"
authors = ["paul@colomiets.name"]

[dependencies]
rustc-serialize = "0.3"
argparse = "0.2"
quick-error = "1.0.0"

